export LC_ALL=de_DE.UTF-8


export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="wezm"

# use `keychain` to manage ssh-keys
eval $(keychain --eval --quiet --confhost ~/.ssh/id_ed25519)

plugins=(\
    docker \
    docker-compose \
    dotenv \
    fzf \
    git \
    kubectl \
    virtualenvwrapper\
    zsh-autosuggestions \
    # zsh-syntax-highlighting \
)

source $ZSH/oh-my-zsh.sh

if type kubectl &>/dev/null; then
    source <(kubectl completion zsh)
fi
if type helm &>/dev/null; then
    source <(helm completion zsh)
fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

HISTFILE=~/.histfile
HISTSIZE=5000000
SAVEHIST=5000000
unsetopt beep
bindkey -v

zstyle :compinstall filename "$HOME/.zshrc"

# make newly installed executables available to completion
zstyle ':completion:*' rehash true

# history search
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

[[ -n "${key[Up]}"   ]] && bindkey "${key[Up]}"   up-line-or-beginning-search
[[ -n "${key[Down]}" ]] && bindkey "${key[Down]}" down-line-or-beginning-search

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /usr/local/bin/virtualenvwrapper.sh ] && . /usr/local/bin/virtualenvwrapper.sh

export BW_SESSION=$(bw get password bitwarden_session_id)
export NVM_DIR="$HOME/.nvm"
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export PYTHONSTARTUP="$(python3 -m jedi repl)"
export PATH=$PATH:~/.local/bin:~/.cargo/bin
export FZF_DEFAULT_OPTS="--no-mouse --height 60% -1 --reverse --multi --inline-info \
--preview='[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || \
(bat --color=always {} || cat {}) 2> /dev/null | head -300' \
--bind='f3:execute(bat {} || less -f {}),f2:toggle-preview,shift-up:preview-page-up,shift-down:preview-page-down,ctrl-a:select-all+accept,ctrl-y:execute-silent(echo {+} | pbcopy)'"
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# bind -x '"\C-p": nvim $(fzf);'
export BAT_CONFIG_DIR="~/.config/bat/config"
export CARGO_TARGET_DIR="$HOME/.cargo/target"
export PINENTRY_USER_DATA=USE_TTY=1
export CLICOLOR=1

export GITLAB_USER=skriems
export GITLAB_TOKEN=$(bw get password GITLAB_TOKEN)
export KUBECONFIG=$HOME/sailrs/k3s/fleet/kubeconfig.yaml:$HOME/sailrs/k3s/fleet-playground/kubeconfig.yaml
export TF_VAR_hcloud_token=$(bw get password hcloud_token_sailrs)
# export TF_VAR_hcloud_token=$(bw get password hcloud_token_playground)
export TF_VAR_ssh_private_key=$HOME/.ssh/id_terraform
export TF_VAR_ssh_public_key=$HOME/.ssh/id_terraform.pub

alias rust-musl-builder='docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder'
alias ls='ls --color=auto'
alias l='ls -l --color=auto'
alias ll="ls -la --color=auto"
alias df="df -h"
alias du="du -h"

[ -f "$HOME/.zshrc_platform" ] && source "$HOME/.zshrc_platform"
