version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
    networks:
      - proxy-tier
    restart: unless-stopped

  le:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  nc_web:
    image: nginx
    container_name: nc_web
    links:
      - nc
      - collabora
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nextcloud:/var/www/html
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${MAIL}
    networks:
      - proxy-tier
    restart: unless-stopped

  nc:
    image: nextcloud:fpm
    container_name: nc
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    networks:
      - proxy-tier
    restart: unless-stopped

  db:
    image: postgres:9-alpine
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWD}
      LANG: de_DE.utf8
    restart: unless-stopped
    networks:
      - proxy-tier

  redis:
    image: redis
    container_name: redis
    networks:
      - proxy-tier
    restart: unless-stopped

  collabora:
    image: collabora/code
    container_name: collabora
    cap_add:
      - MKNOD
    environment:
      - domain=${DOMAIN}
    networks:
      - proxy-tier
    restart: unless-stopped

volumes:
  db:
  conf.d:
  vhost.d:
  certs:
  dhparam:
  html:
  nextcloud:
  ncapps:
  ncconfig:
  ncdata:

networks:
  proxy-tier:
    external:
      name: nginx-proxy
