projects = { "/Users/skriems/repos/priv/skriems" = { trust_level = "trusted" }, "/Users/skriems/repos/lifestage/code/b2c" = { trust_level = "trusted" } }

model = "gpt-5-codex"
model_provider = "openai"

auto_upgrade_enabled = true
tui = { theme = { name = "dark-oled-black-pro" }, alternate_screen = true }

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]
