debug = false
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[docker]
swarmmode = true
endpoint = "unix:///var/run/docker.sock"
domain = "example.tld"
watch = true
exposedbydefault = false

# Enable retry sending request if network error
[retry]
# attempts = 3

[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.traefik]
  address = ":8080"
    [entryPoints.traefik.auth.basic]
    # `openssl passwd -apr1`
    users = [
        "<user>:<pw>"
    ]
  [entryPoints.https]
  address = ":443"
  compress = true
  [entryPoints.https.tls]

[acme]
email = "webmaster@example.tld"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true
## For Let's Encrypt testing:
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
[acme.httpChallenge]
entryPoint = "http"
