## global config
set-option -g default-shell /opt/homebrew/bin/fish

# make tmux advertise proper color support
set -g default-terminal "tmux-256color"
set -ag terminal-features ",xterm-256color:RGB,screen-256color:RGB,tmux-256color:RGB"

# enable modified enter key
set -g extended-keys on

set -g mouse on
set -g @scroll-speed-num-lines-per-scroll 1

set-window-option -g mode-keys vi
set-option -g status-keys vi

bind -Tcopy-mode WheelUpPane send -N1 -X scroll-up
bind -Tcopy-mode WheelDownPane send -N1 -X scroll-down

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# nvim:checkhealth wants 
set-option -sg escape-time 10
set-option -g focus-events on

## plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-logging'

### Tokyo Night Theme
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme night              # night (default) | storm | moon | day
set -g @tokyo-night-tmux_transparent 1            # transparent background
set -g @tokyo-night-tmux_show_git 1               # local git status
set -g @tokyo-night-tmux_show_wbg 1               # GitHub / GitLab stats
set -g @tokyo-night-tmux_show_netspeed 1          # network speed
# set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
# set -g @tokyo-night-tmux_show_music 1           # now playing
set -g @tokyo-night-tmux_show_path 1              # current path
# set -g @tokyo-night-tmux_show_hostname 1        # machine hostname
# set -g @tokyo-night-tmux_show_datetime 0
# set -g @tokyo-night-tmux_show_netspeed 0

run '~/.tmux/plugins/tpm/tpm'
