return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    auto_install = true,
    ensure_installed = {
      "bash",
      "diff",
      "dockerfile",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "html",
      "java",
      "javascript",
      "jq",
      "json",
      "llvm",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "mermaid",
      "php",
      "phpdoc",
      "prisma",
      "python",
      "scheme",
      "scss",
      "regex",
      "rust",
      "sql",
      "swift",
      "svelte",
      "terraform",
      "toml",
      "typescript",
      "vue",
      "yaml",
    },
  },
}
